### PR TITLE
Added compatiblity with java versions 6 and 7

### PR DESCRIPTION
**Pull request by benfortuna**

### CODE REVIEW

**Comment by noamt** [comment]
Thanks for that !

**Comment by szpak** [comment]
@benfortuna Unfortunately it doesn't work as expected with Java 6 - https://travis-ci.org/noamt/rest-gradle-plugin/jobs/131240617.

**Comment by benfortuna** [comment]
Ok I will create a new PR shortly to change compatibility to 1.7.

**Comment by benfortuna** [comment]
Ah ok, apologies I should have committed a Travis ci config change also.
Anyway I think java 7 support is the most important (for me anyway). :-)
On 19 May 2016 6:15 am, "Marcin Zajączkowski" <notifications@github.com>
wrote:

@benfortuna <https://github.com/benfortuna> Unfortunately it doesn't work
as expected with Java 6 -
https://travis-ci.org/noamt/rest-gradle-plugin/jobs/131240617.

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/noamt/rest-gradle-plugin/pull/19#issuecomment-220144459>

**Comment by noamt** [comment]
Not need to PR. I'll just push a revert.

**Comment by benfortuna** [comment]
Have a look at PR #21 first pls.

**Pull request merged**
